force-app/main/default/objects/devise__c/fields/Taux_change__c.field-meta.xml
<CustomField>
    <fullName>Taux_change__c</fullName>
    <label>Taux de change</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/LigneFacturation__c.object-meta.xml
<CustomObject>
    <label>Ligne de facturation</label>
    <nameField>
        <label>Ligne Facturation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneFacturation__c/fields/Contrevaleur_montant_total_PEC__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC__c</fullName>
    <formula>Montant_total_PEC_devises__c * Taux_change__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrevaleur du montant total PEC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Copaiement_devises__c.field-meta.xml
<CustomField>
    <fullName>Copaiement_devises__c</fullName>
    <formula>Montant_total_devises__c -  Montant_total_PEC_devises__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copaiement en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Date_heure_taux_change__c.field-meta.xml
<CustomField>
    <fullName>Date_heure_taux_change__c</fullName>
    <label>Date et heure du taux de change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Detail_moyen__c.field-meta.xml
<CustomField>
    <fullName>Detail_moyen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Détail du moyen</label>
    <referenceTo>moyen_du_service__c</referenceTo>
    <relationshipLabel>Détail du moyen</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Detail_moyen_frais_medicaux__c.field-meta.xml
<CustomField>
    <fullName>Detail_moyen_frais_medicaux__c</fullName>
    <label>Détail du moyen frais médicaux</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accompagnant</fullName>
            </value>
            <value>
                <fullName>Ambulance</fullName>
            </value>
            <value>
                <fullName>Autres services</fullName>
            </value>
            <value>
                <fullName>Bloc</fullName>
            </value>
            <value>
                <fullName>Chambre</fullName>
            </value>
            <value>
                <fullName>Forfait</fullName>
            </value>
            <value>
                <fullName>Frais de sejour</fullName>
                <label>Frais de séjour</label>
            </value>
            <value>
                <fullName>Home MED</fullName>
            </value>
            <value>
                <fullName>Honoraires</fullName>
            </value>
            <value>
                <fullName>Imagerie</fullName>
            </value>
            <value>
                <fullName>Implant_Prothese</fullName>
                <label>Implant / Prothèse</label>
            </value>
            <value>
                <fullName>Kine</fullName>
                <label>Kiné</label>
            </value>
            <value>
                <fullName>Laboratoire</fullName>
            </value>
            <value>
                <fullName>Molecule couteuse</fullName>
                <label>Molécule coûteuse</label>
            </value>
            <value>
                <fullName>Pharmacie</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
                <isActive>false</isActive>
                <label>Franchise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Devise__c.field-meta.xml
<CustomField>
    <fullName>Devise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Devise</label>
    <referenceTo>devise__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Finance__c.field-meta.xml
<CustomField>
    <fullName>Finance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance</label>
    <referenceTo>facture_devis__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Franchise_devises__c.field-meta.xml
<CustomField>
    <fullName>Franchise_devises__c</fullName>
    <label>Franchise en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Garantie_du_service__c.field-meta.xml
<CustomField>
    <fullName>Garantie_du_service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantie</label>
    <referenceTo>garantie_du_service__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_de_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Montant_total_devises__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_devises__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Montant_total_PEC_devises__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_PEC_devises__c</fullName>
    <formula>IF((ISNULL(Plafond_devises__c)|| (Plafond_devises__c==0)), Montant_total_devises__c  * Pourcentage_PEC__c,IF( Montant_total_devises__c&gt; Plafond_devises__c , Plafond_devises__c* Pourcentage_PEC__c, Montant_total_devises__c  * Pourcentage_PEC__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant total PEC en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Plafond_devises__c.field-meta.xml
<CustomField>
    <fullName>Plafond_devises__c</fullName>
    <label>Plafond en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Pourcentage_PEC__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_PEC__c</fullName>
    <label>Pourcentage de PEC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Quantite__c.field-meta.xml
<CustomField>
    <fullName>Quantite__c</fullName>
    <label>Quantité</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Taux_change__c.field-meta.xml
<CustomField>
    <fullName>Taux_change__c</fullName>
    <label>Taux de change</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/TECH_Garantie__c.field-meta.xml
<CustomField>
    <fullName>TECH_Garantie__c</fullName>
    <label>TECH_Garantie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/TECH_Moyen__c.field-meta.xml
<CustomField>
    <fullName>TECH_Moyen__c</fullName>
    <label>TECH_Moyen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP02CloneLigneFacturation.cls
public with sharing class AP02CloneLigneFacturation {
    @InvocableMethod(label='Clone Ligne Facturation' description='Iterate over students, classes and payments and create junction records')
    public static void cloneLigneFacturation(List<InputWrapper> inp){
        String oldDevis = inp.get(0).idDevisToClone;
        String newDevis = inp.get(0).newDevis;
        List<LigneFacturation__c> lstLigne = computeFacturation(newDevis,oldDevis);
        if(!lstLigne.isEmpty()){
            insert lstLigne;
        }
    }

    public static List<LigneFacturation__c> computeFacturation(String newDevis,String oldDevis){
        List<LigneFacturation__c> lstLigne= new List<LigneFacturation__c>();
        for(LigneFacturation__c fac:  [SELECT Contrevaleur_montant_total_PEC__c, Copaiement_devises__c, CreatedById, Date_heure_taux_change__c, Detail_moyen__c, Detail_moyen_frais_medicaux__c, Devise__c, Finance__c, Franchise_devises__c, Garantie_du_service__c, Id, Montant_total_PEC_devises__c, Montant_total_devises__c, Name, OwnerId, Plafond_devises__c, Pourcentage_PEC__c, Quantite__c, RecordTypeId, SystemModstamp, TECH_Garantie__c, TECH_Moyen__c, Taux_change__c FROM LigneFacturation__c WHERE Finance__c =: oldDevis]){
            LigneFacturation__c currFac = fac.clone(false, true, false, false);
            currFac.Finance__c= newDevis;
            lstLigne.add(currFac);
        }

        return lstLigne;
    }

    public class InputWrapper{
        
        @InvocableVariable
        public String idDevisToClone;

        @InvocableVariable
        public String  newDevis;
    }
    
    
}