force-app/main/default/objects/facture_devis__c/facture_devis__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Numéro de devis / facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/facture_devis__c/fields/Contrevaleur_en_euros_validee_Ebury__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_en_euros_validee_Ebury__c</fullName>
    <label>Contrevaleur en euros validée Ebury</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Contrevaleur_montant_total_PEC_c__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC_c__c</fullName>
    <label>Contrevaleur en euros estimée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Date_de_mise_en_paiement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_mise_en_paiement__c</fullName>
    <label>Date de mise en paiement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <formula>IF( 
						RecordType.Name == &quot;Facture&quot;, 
						IF( 
										Bon_a_payer_rapide__c, 
										Date_de_mise_en_paiement__c + 5, 
										Date_reception_facture__c + Emetteur_facture__r.Modalites_paiement__c), 
						IF( 
										RecordType.Name == &quot;Remboursement&quot;, 
										Date_reception_facture__c + Modalites_de_remboursement__c, 
										NULL ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date d’échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Date_reception_facture__c.field-meta.xml
<CustomField>
    <fullName>Date_reception_facture__c</fullName>
    <label>Date de réception</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/DestinatairePaiement__c.field-meta.xml
<CustomField>
    <fullName>DestinatairePaiement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destinataire du paiement</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Finances (Destinataire du paiement)</relationshipLabel>
    <relationshipName>Finances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Emetteur_facture__c.field-meta.xml
<CustomField>
    <fullName>Emetteur_facture__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Emetteur facture</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Finances (Emetteur facture)</relationshipLabel>
    <relationshipName>Finances1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Formule__c.field-meta.xml
<CustomField>
    <fullName>Formule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Formule</label>
    <referenceTo>formule_vyv_ia__c</referenceTo>
    <relationshipLabel>Finances</relationshipLabel>
    <relationshipName>Finances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Lot_paiement__c.field-meta.xml
<CustomField>
    <fullName>Lot_paiement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot de paiement</label>
    <referenceTo>Lot_paiement__c</referenceTo>
    <relationshipLabel>Finances</relationshipLabel>
    <relationshipName>Finances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/ModeleEconomique__c.field-meta.xml
<CustomField>
    <fullName>ModeleEconomique__c</fullName>
    <label>Modèle économique</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>Prestation</fullName>
            </value>
            <value>
                <fullName>Prime/Prestation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/montant_total__c.field-meta.xml
<CustomField>
    <fullName>montant_total__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyse</fullName>
            </value>
            <value>
                <fullName>Prise en charge</fullName>
            </value>
            <value>
                <fullName>Consultation medicale</fullName>
                <label>Consultation médicale</label>
            </value>
            <value>
                <fullName>Conformite</fullName>
                <label>Conformité</label>
            </value>
            <value>
                <fullName>Traitement</fullName>
            </value>
            <value>
                <fullName>Controle</fullName>
                <label>Contrôle</label>
            </value>
            <value>
                <fullName>Paiement_Facturation</fullName>
                <label>Paiement / Facturation</label>
            </value>
            <value>
                <fullName>Bon a payer</fullName>
                <isActive>false</isActive>
                <label>Bon à payer</label>
            </value>
            <value>
                <fullName>Devis rejete</fullName>
                <isActive>false</isActive>
                <label>Devis rejeté</label>
            </value>
            <value>
                <fullName>Devis valide</fullName>
                <isActive>false</isActive>
                <label>Devis validé</label>
            </value>
            <value>
                <fullName>Echec Paiement</fullName>
                <isActive>false</isActive>
                <label>Echec Paiement</label>
            </value>
            <value>
                <fullName>En attente demande de pieces</fullName>
                <isActive>false</isActive>
                <label>En attente demande de pièces</label>
            </value>
            <value>
                <fullName>En attente validation medicale</fullName>
                <isActive>false</isActive>
                <label>En attente validation médicale</label>
            </value>
            <value>
                <fullName>Envoye Ebury</fullName>
                <isActive>false</isActive>
                <label>Envoyé Ebury</label>
            </value>
            <value>
                <fullName>Facture payee</fullName>
                <isActive>false</isActive>
                <label>Facture payée</label>
            </value>
            <value>
                <fullName>Facture refacturee</fullName>
                <isActive>false</isActive>
                <label>Facture refacturée</label>
            </value>
            <value>
                <fullName>Facture rejetee</fullName>
                <isActive>false</isActive>
                <label>Facture rejetée</label>
            </value>
            <value>
                <fullName>Mise en paiement</fullName>
                <isActive>false</isActive>
                <label>Mise en paiement</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
                <isActive>false</isActive>
                <label>Qualification</label>
            </value>
            <value>
                <fullName>Remboursement refacture</fullName>
                <isActive>false</isActive>
                <label>Remboursement refacturé</label>
            </value>
            <value>
                <fullName>Remboursement rejete</fullName>
                <isActive>false</isActive>
                <label>Remboursement rejeté</label>
            </value>
            <value>
                <fullName>Rembourse</fullName>
                <isActive>false</isActive>
                <label>Remboursé</label>
            </value>
            <value>
                <fullName>Validation DG</fullName>
                <isActive>false</isActive>
                <label>Validation DG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/TECH_statusbar__c.field-meta.xml
<CustomField>
    <fullName>TECH_statusbar__c</fullName>
    <label>TECH_statusbar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/recordTypes/Facture.recordType-meta.xml
<RecordType>
    <fullName>Facture</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/facture_devis__c/recordTypes/Remboursement.recordType-meta.xml
<RecordType>
    <fullName>Remboursement</fullName>
    <active>true</active>
    <label>Remboursement</label>
</RecordType>

force-app/main/default/objects/Lot_paiement__c/Lot_paiement__c.object-meta.xml
<CustomObject>
    <label>Lot de paiement</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot de paiements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot_paiement__c/fields/Montant_total__c.field-meta.xml
<CustomField>
    <fullName>Montant_total__c</fullName>
    <label>Montant total en euros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Montant_total_en_euros_valide__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_en_euros_valide__c</fullName>
    <label>Montant total en euros validé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Nombre_elements__c.field-meta.xml
<CustomField>
    <fullName>Nombre_elements__c</fullName>
    <label>Nombre d’éléments dans lot de paiement</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
                <default>true</default>
                <label>Qualification</label>
            </value>
            <value>
                <fullName>Pret</fullName>
                <label>Prêt</label>
            </value>
            <value>
                <fullName>Envoye Ebury</fullName>
                <label>Envoyé Ebury</label>
            </value>
            <value>
                <fullName>Traitement</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Paiement</fullName>
            </value>
            <value>
                <fullName>Echec</fullName>
            </value>
            <value>
                <fullName>A payer</fullName>
                <isActive>false</isActive>
                <label>A payer</label>
            </value>
            <value>
                <fullName>A synchroniser</fullName>
                <isActive>false</isActive>
                <label>A synchroniser</label>
            </value>
            <value>
                <fullName>Echec paiement</fullName>
                <isActive>false</isActive>
                <label>Echec paiement</label>
            </value>
            <value>
                <fullName>En cours de synchronisation</fullName>
                <isActive>false</isActive>
                <label>En cours de synchronisation</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
            <value>
                <fullName>Traité</fullName>
                <isActive>false</isActive>
                <label>Traité</label>
            </value>
            <value>
                <fullName>Validé</fullName>
                <isActive>false</isActive>
                <label>Validé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP_DatatableUtils.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-06-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AP_DatatableUtils {
   
    static List<String> lstRecordType = new List<String>{'Remboursement' ,'Facture'};
    static List<String> lstStatut = new List<String>{'Mise en paiement' ,'Echec Paiement'};

    @AuraEnabled
    public static List<facture_devis__c> getFinance(Integer countLimit, Integer offset, String searchValue, Map<String, List<String>> mapFilter, String dateFilter, Boolean visualisation, String recordId){
        //try {
            //String query = 'SELECT Id, Name, Account.Name, Date_echeance__c, StageName, Probability, Amount FROM Opportunity WHERE Visualised__c = ' + visualisation + ' ';
            String query='';
            if(visualisation){
                         query = 'select id, Name, service__r.CaseNumber, Date_reception_facture__c, Montant_pris_en_charge__c, devise_lookup__r.Code_ISO4217__c,Contrevaleur_montant_total_PEC_c__c,Emetteur_facture__r.Name,DestinatairePaiement__r.Name,Date_echeance__c,Date_de_mise_en_paiement__c,GrandCompte__c,Formule__r.Name,ModeleEconomique__c,Statut__c,service__c,devise_lookup__c,Emetteur_facture__c,DestinatairePaiement__c,Formule__c from facture_devis__c where Lot_paiement__c = \''+recordId+ '\' ';
            }
            else{
              
                query = 'select id, Name, service__r.CaseNumber, Date_reception_facture__c, Montant_pris_en_charge__c, devise_lookup__r.Code_ISO4217__c,Contrevaleur_montant_total_PEC_c__c,Emetteur_facture__r.Name,DestinatairePaiement__r.Name,Date_echeance__c,Date_de_mise_en_paiement__c,GrandCompte__c,Formule__r.Name,ModeleEconomique__c,Statut__c,service__c,devise_lookup__c,Emetteur_facture__c,DestinatairePaiement__c,Formule__c from facture_devis__c where Lot_paiement__c = null and (Statut__c =\'Mise en paiement\' or Statut__c =\'Echec Paiement\') and (RecordType.Name=\'Facture\' OR RecordType.Name =\'Remboursement\') ';
                    //  query = 'select id, Name, service__r.CaseNumber, Date_reception_facture__c, Montant_pris_en_charge__c, devise_lookup__r.Code_ISO4217__c,Contrevaleur_montant_total_PEC_c__c,Emetteur_facture__r.Name,DestinatairePaiement__r.Name,Date_echeance__c,Date_de_mise_en_paiement__c,GrandCompte__c,Formule__r.Name,ModeleEconomique__c,Statut__c,service__c,devise_lookup__c,Emetteur_facture__c,DestinatairePaiement__c,Formule__c from facture_devis__c where Lot_paiement__c = null and (Statut__c IN "'+String.join(lstStatut, '","')+') and (RecordType.DeveloperName IN "'+String.join(lstRecordType, '","')+') ';
                     

            }
            query= buildQuery(mapFilter,searchValue,query,dateFilter);

            // if (searchValue != '') {
            //     query = query + ' AND Name LIKE \'%' + String.escapeSingleQuotes(searchValue) + '%\' ';
            //     if (filterQuery != '') {
            //         query = query + ' AND ' + filterQuery;
            //     }
            // } else if (filterQuery != '') {
            //     query = query + ' AND ' + filterQuery;
            // }
            // if (dateFilter == 'Passée') query = query + ' AND Date_echeance__c < TODAY ';
            // else if (dateFilter == 'Aujourd\'hui') query = query + ' AND Date_echeance__c = TODAY ';
            // else if (dateFilter == '7 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:7 ';
            // else if (dateFilter == '15 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:15 ';
            // else if (dateFilter == '30 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:30 ';

            return Database.query(query + ' LIMIT ' + countLimit + ' OFFSET ' + offset);
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }

    @AuraEnabled
    public static Integer getNumberFinances(String searchValue, Map<String, List<String>> mapFilter, String dateFilter, Boolean visualisation, String recordId){
        //try {
            system.debug(recordId);
            String query='';
            if(visualisation){

                query = 'select count(id) NumberRows from facture_devis__c where Lot_paiement__c = \''+recordId+ '\' ';
            }
            else{
                query = 'select count(id) NumberRows from facture_devis__c where Lot_paiement__c = null and (Statut__c =\'Mise en paiement\' or Statut__c =\'Echec Paiement\') and (RecordType.Name=\'Facture\' OR RecordType.Name =\'Remboursement\') ';

            }
            query= buildQuery(mapFilter,searchValue, query,dateFilter);

            // if (searchValue != '') {
            //     query = query + ' AND Name LIKE \'%' + String.escapeSingleQuotes(searchValue) + '%\' ';
            //     if (filterQuery != '') {
            //         query = query + ' AND ' + filterQuery;
            //     }
            // } else if (filterQuery != '') {
            //     query = query + ' AND '+ filterQuery;
            // }

            // if (dateFilter == 'Passée') query = query + ' AND Date_echeance__c < TODAY ';
            // else if (dateFilter == 'Aujourd\'hui') query = query + ' AND Date_echeance__c = TODAY ';
            // else if (dateFilter == '7 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:7 ';
            // else if (dateFilter == '15 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:15 ';
            // else if (dateFilter == '30 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:30 ';

            system.debug(query);
            return (Integer)Database.query(query)[0].get('NumberRows');
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // } 
    }

    @AuraEnabled
    public static GlobalDatasetWrapper getGlobalDataset(String searchValue, Map<String, List<String>> mapFilter, String dateFilter, Boolean visualisation, String recordId){
        //try {
            String query='';
            if(visualisation){
                query = 'SELECT devise_lookup__r.Code_ISO4217__c, Emetteur_facture__r.Name, RecordType.Name,ModeleEconomique__c, toLabel(Statut__c), Contrevaleur_montant_total_PEC_c__c,Contrevaleur_en_euros_validee_Ebury__c,GrandCompte__c FROM facture_devis__c WHERE Lot_paiement__c = \''+recordId+ '\' ';
            }
            else {
                query = 'SELECT devise_lookup__r.Code_ISO4217__c, Emetteur_facture__r.Name, RecordType.Name,ModeleEconomique__c, toLabel(Statut__c), Contrevaleur_montant_total_PEC_c__c ,Contrevaleur_en_euros_validee_Ebury__c,GrandCompte__c FROM facture_devis__c WHERE Lot_paiement__c = null and (Statut__c =\'Mise en paiement\' or Statut__c =\'Echec Paiement\') and (RecordType.Name=\'Facture\' OR RecordType.Name =\'Remboursement\') ';

            }
            //system.debug(mapFilter);
            query= buildQuery(mapFilter,searchValue,query,dateFilter);

            // if (searchValue != '') {
            //     query = query + ' AND Name LIKE \'%' + String.escapeSingleQuotes(searchValue) + '%\' ';
            //     if (filterQuery != '') {
            //         query = query + ' AND ' + filterQuery;
            //     }
            // } else if (filterQuery != '') {
            //     query = query + ' AND '+ filterQuery;
            // }
            // if (dateFilter == 'Passée') query = query + ' AND Date_echeance__c < TODAY ';
            // else if (dateFilter == 'Aujourd\'hui') query = query + ' AND Date_echeance__c = TODAY ';
            // else if (dateFilter == '7 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:7 ';
            // else if (dateFilter == '15 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:15 ';
            // else if (dateFilter == '30 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:30 ';
           
            system.debug(query);

            List<facture_devis__c> lstFinance = Database.query(query);

            //List<Opportunity> lstOpportunity = [SELECT StageName, Account.Name, Amount FROM Opportunity];
            
            GlobalDatasetWrapper wrapper = new GlobalDatasetWrapper();
            wrapper.totalAmount = 0;
            wrapper.totalValide = 0;
            if (!lstFinance.isEmpty()) {
                Set<String> setDevise = new Set<String>();
                Set<String> setPrestataire = new Set<String>();
                Set<String> setTypeFinance = new Set<String>();
                Set<String> setModeleEconomique = new Set<String>();
                Set<String> setGrandCompte = new Set<String>();
                Set<String> setStatut = new Set<String>();
                for (facture_devis__c  fin : lstFinance) {
                    if (fin.devise_lookup__r.Code_ISO4217__c != NULL) setDevise.add(fin.devise_lookup__r.Code_ISO4217__c);
                    if (fin.Emetteur_facture__r.Name != NULL) setPrestataire.add(fin.Emetteur_facture__r.Name);
                    if (fin.RecordType.Name != NULL) setTypeFinance.add(fin.RecordType.Name);
                    if (fin.ModeleEconomique__c != NULL) setModeleEconomique.add(fin.ModeleEconomique__c);
                    if (fin.Statut__c != NULL) setStatut.add(fin.Statut__c);
                    if (fin.GrandCompte__c != NULL) setGrandCompte.add(fin.GrandCompte__c);
                    if (fin.Contrevaleur_montant_total_PEC_c__c != NULL) wrapper.totalAmount += fin.Contrevaleur_montant_total_PEC_c__c;
                    if (fin.Contrevaleur_en_euros_validee_Ebury__c != NULL) wrapper.totalValide += fin.Contrevaleur_en_euros_validee_Ebury__c;
                }
                wrapper.Devise = JSON.serialize(setDevise);
                wrapper.Prestataire = JSON.serialize(setPrestataire);
                wrapper.TypeFinance = JSON.serialize(setTypeFinance);
                wrapper.ModeleEconomique = JSON.serialize(setModeleEconomique);
                wrapper.Statut = JSON.serialize(setStatut);
                wrapper.grandCompte = JSON.serialize(setGrandCompte);
            }
            return wrapper;
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }

    @AuraEnabled
    public static List<Id> getAllId(String searchValue, Map<String, List<String>> mapFilter, String dateFilter, Boolean visualisation, String recordId){
        //try {
            //return new List<Id>(new Map<Id, Opportunity>([SELECT Id FROM Opportunity]).keySet());
            
           // String query = 'SELECT Id FROM  WHERE Visualised__c = ' + visualisation + ' ';
           String query='';
           if(visualisation){
                query = 'SELECT Id FROM facture_devis__c WHERE Lot_paiement__c = \''+recordId+ '\' ';
            }
            else {
                query = 'SELECT Id FROM facture_devis__c WHERE Lot_paiement__c = null and (Statut__c =\'Mise en paiement\' or Statut__c =\'Echec Paiement\') and (RecordType.Name=\'Facture\' OR RecordType.Name =\'Remboursement\') ';

            }
            system.debug(mapFilter);
            query= buildQuery(mapFilter, searchValue,query,dateFilter);

            // if (searchValue != '') {
            //     query = query + ' AND Name LIKE \'%' + String.escapeSingleQuotes(searchValue) + '%\' ';
            //     if (filterQuery != '') {
            //         query = query + ' AND ' + filterQuery;
            //     }
            // } else if (filterQuery != '') {
            //     query = query + ' AND '+ filterQuery;
            // }
            // if (dateFilter == 'Passée') query = query + ' AND Date_echeance__c < TODAY ';
            // else if (dateFilter == 'Aujourd\'hui') query = query + ' AND Date_echeance__c = TODAY ';
            // else if (dateFilter == '7 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:7 ';
            // else if (dateFilter == '15 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:15 ';
            // else if (dateFilter == '30 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:30 ';

            query += ' order by Id';

            List<facture_devis__c> lstFinance = Database.query(query);

            List<Id> lstFinId = new List<Id>();

            for (facture_devis__c fin : lstFinance) {
                lstFinId.add(fin.Id);
            } 

            return lstFinId;

        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }

    @AuraEnabled
    public static void updateFin(List<String> lstId, String recordId, Boolean remove ){
        //try {
           
            List<facture_devis__c> lstFin = new List<facture_devis__c>();
            if(remove){
                for (String finId : lstId) {
                    lstFin.add(new facture_devis__c(Id = finId, Lot_paiement__c = null));
                }
            }else{
                for (String finId : lstId) {
                    lstFin.add(new facture_devis__c(Id = finId, Lot_paiement__c = recordId));
                }
            }
          
            update lstFin;
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }

    @AuraEnabled
    public static void saveTotalAmount(String recordId, Double totalAmount, Double totalValide) {
        //try {
            Lot_paiement__c ldp = new Lot_paiement__c(Id = recordId, Montant_total__c = totalAmount, Montant_total_en_euros_valide__c = totalValide);
            
            update ldp;
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }
    @AuraEnabled
    public static void saveNumberElement(String recordId, Integer numberElement) {
        //try {
            Lot_paiement__c ldp = new Lot_paiement__c(Id = recordId, Nombre_elements__c = numberElement);
            
            update ldp;
        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }
    }
    @AuraEnabled
    public static void saveFinanceStatus(String recordId){
        //try {
            String query = 'SELECT Id,RecordType.Name, toLabel(Statut__c),TECH_statusbar__c FROM facture_devis__c WHERE Lot_paiement__c = \''+recordId+ '\' ';
            List<facture_devis__c> lstFinance = Database.query(query);
            system.debug('techbar'+lstFinance);
            List<facture_devis__c> lstFin = new List<facture_devis__c>();
            if (!lstFinance.isEmpty()) {
                for (facture_devis__c  fin : lstFinance) {
                    String inputString = fin.TECH_statusbar__c;
                    String[] outputArray = inputString.substring(1, inputString.length() - 1).split(',');

                    // Trim each element in the array to remove extra spaces and quotes
                    // for(Integer i = 0; i < outputArray.size(); i++) {
                    //     outputArray[i] = outputArray[i].trim().replaceAll('"', '');
                    // }
                    if(fin.RecordType.Name =='Facture'){
                        if(fin.Statut__c=='Mise en Paiement'){
                            outputArray[5] = '"completed"';
                            outputArray[6] = '"completed"';
                        }
                        if(fin.Statut__c=='Echec Paiement'){
                            outputArray[5] = '"completed"';
                            outputArray[6] = '"completed"';
                            outputArray[7] = '"not yet"';
                        }

                    }else{
                        if(fin.Statut__c=='Mise en Paiement'){
                            outputArray[4] = '"completed"';
                            outputArray[5] = '"completed"';
                        }
                        if(fin.Statut__c=='Echec Paiement'){
                            outputArray[4] = '"completed"';
                            outputArray[5] = '"completed"';
                            outputArray[6] = '"not yet"';
                        }
                    }
                    System.debug(outputArray);
                    // String[] quotedArray = new List<String>();
                    // for (String element : outputArray) {
                    //     quotedArray.add('"' + element + '"');
                    // }
                    String statusbar = '[' +String.join(outputArray, ',')+ ']';
                    system.debug(statusbar);
                    lstFin.add(new facture_devis__c(Id = fin.Id, Statut__c = 'Envoye Ebury', TECH_statusbar__c = statusbar));
                }
                update lstFin;
            }

        // } catch (Exception e) {
        //     throw new AuraHandledException(e.getMessage());
        // }

    }

    public class GlobalDatasetWrapper {
        
        @AuraEnabled
        public String Devise;
        @AuraEnabled
        public String Prestataire;
        @AuraEnabled
        public String TypeFinance;
        @AuraEnabled
        public String ModeleEconomique;
        @AuraEnabled
        public String Statut;
        @AuraEnabled
        public Decimal totalAmount;
        @AuraEnabled
        public Decimal totalValide;
        @AuraEnabled
        public String grandCompte;

    }

    public static String buildQuery(Map<String, List<String>> mapFilter,String searchValue ,String query, String dateFilter){
        String filterQuery = '';
            for (String field : mapFilter.keySet()) {
                if (mapFilter.get(field).size() > 0) {
                    if (filterQuery != '') filterQuery += 'AND ';
                    filterQuery = filterQuery + field + ' IN (';
                    for (Integer i = 0; i < mapFilter.get(field).size(); i++) {
                        if (i != 0) filterQuery += ', ';
                        filterQuery = filterQuery + '\'' + String.escapeSingleQuotes(mapFilter.get(field)[i]) + '\''; 
                        if (i == mapFilter.get(field).size() - 1) filterQuery += ') ';
                    }
                }
            }
            if (searchValue != '') {
                query = query + ' AND Name LIKE \'%' + String.escapeSingleQuotes(searchValue) + '%\' ';
                if (filterQuery != '') {
                    query = query + ' AND ' + filterQuery;
                }
            } else if (filterQuery != '') {
                query = query + ' AND '+ filterQuery;
            }

            if (dateFilter == 'Passée') query = query + ' AND Date_echeance__c < TODAY ';
            else if (dateFilter == 'Aujourd\'hui') query = query + ' AND Date_echeance__c = TODAY ';
            else if (dateFilter == '7 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:7 ';
            else if (dateFilter == '15 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:15 ';
            else if (dateFilter == '30 prochains jours') query = query + ' AND Date_echeance__c > TODAY AND Date_echeance__c <= NEXT_N_DAYS:30 ';
        return query;
    }
}