force-app/main/default/objects/facture_devis__c/facture_devis__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Numéro de devis / facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/facture_devis__c/fields/Contrevaleur_montant_total_PEC_c__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC_c__c</fullName>
    <label>Contrevaleur en euros estimée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/montant_total__c.field-meta.xml
<CustomField>
    <fullName>montant_total__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/LigneFacturation__c.object-meta.xml
<CustomObject>
    <label>Ligne de facturation</label>
    <nameField>
        <label>Ligne Facturation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneFacturation__c/fields/Contrevaleur_montant_total_PEC__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC__c</fullName>
    <formula>Montant_total_PEC_devises__c * Taux_change__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrevaleur du montant total PEC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Copaiement_devises__c.field-meta.xml
<CustomField>
    <fullName>Copaiement_devises__c</fullName>
    <formula>Montant_total_devises__c -  Montant_total_PEC_devises__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copaiement en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Finance__c.field-meta.xml
<CustomField>
    <fullName>Finance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance</label>
    <referenceTo>facture_devis__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Montant_total_devises__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_devises__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Plafond_devises__c.field-meta.xml
<CustomField>
    <fullName>Plafond_devises__c</fullName>
    <label>Plafond en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Pourcentage_PEC__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_PEC__c</fullName>
    <label>Pourcentage de PEC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AP03_LigneFacturation.cls
public with sharing class AP03_LigneFacturation {
    // Method to update LigneFacturation__c records
    @AuraEnabled
    public static void updateLigneDeFacture(String lignesToUpdate) {
        // Deserialize the string back into a list of LigneFacturation__c records
        List<LigneFacturation__c> recordsToUpdate = (List<LigneFacturation__c>) JSON.deserialize(lignesToUpdate, List<LigneFacturation__c>.class);
        
        Decimal montantTotal = 0;
        Decimal montantTotalPEC = 0;
        Decimal copaiement = 0;
        Decimal contrevaleurPEC = 0;

        for (LigneFacturation__c ligneFac : recordsToUpdate) {
            if(ligneFac.Montant_total_devises__c != null) {
                montantTotal += ligneFac.Montant_total_devises__c;
            }
            if(ligneFac.Plafond_devises__c != null && ligneFac.Pourcentage_PEC__c != null) {
                montantTotalPEC += ligneFac.Plafond_devises__c/100 * ligneFac.Pourcentage_PEC__c;
            }
            if(ligneFac.Copaiement_devises__c != null) {
                copaiement += ligneFac.Copaiement_devises__c;
            }
            if(ligneFac.Contrevaleur_montant_total_PEC__c != null) {
                contrevaleurPEC += ligneFac.Contrevaleur_montant_total_PEC__c;
            }
        }

        if(recordsToUpdate[0].Finance__c != null){
            facture_devis__c fin = new facture_devis__c(
                Id = recordsToUpdate[0].Finance__c,
                montant_total__c = montantTotal,
                Montant_pris_en_charge__c = montantTotalPEC,
                Montant_copay__c = copaiement,
                Contrevaleur_montant_total_PEC_c__c = contrevaleurPEC
            );
            update fin;
        }
        update recordsToUpdate;
    }

    // Method to delete LigneFacturation__c records
    @AuraEnabled
    public static void deleteLigneDeFacture(String ligneToDelete) {
        // Deserialize the string back into a list of LigneFacturation__c records
        LigneFacturation__c ligneFac = (LigneFacturation__c) JSON.deserialize(ligneToDelete, LigneFacturation__c.class);

        List<facture_devis__c> fin = [
            SELECT Id, montant_total__c, Montant_pris_en_charge__c, Montant_copay__c,Contrevaleur_montant_total_PEC_c__c
            FROM facture_devis__c
            WHERE Id=:ligneFac.Finance__c
        ];

        if (!fin.isEmpty()){
            if(ligneFac.Montant_total_devises__c != null) {
                fin[0].montant_total__c -= ligneFac.Montant_total_devises__c;
            }
            if(ligneFac.Plafond_devises__c != null && ligneFac.Pourcentage_PEC__c != null) {
                fin[0].Montant_pris_en_charge__c -= ligneFac.Plafond_devises__c/100 * ligneFac.Pourcentage_PEC__c;
            }
            if(ligneFac.Copaiement_devises__c != null) {
                fin[0].Montant_copay__c -= ligneFac.Copaiement_devises__c;
            }
            if(ligneFac.Contrevaleur_montant_total_PEC__c != null) {
                fin[0].Contrevaleur_montant_total_PEC_c__c -= ligneFac.Contrevaleur_montant_total_PEC__c;
            }
            update fin;
        }
       
        delete ligneFac;
    }
}