force-app/main/default/objects/facture_devis__c/facture_devis__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Numéro de devis / facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneFacturation__c/LigneFacturation__c.object-meta.xml
<CustomObject>
    <label>Ligne de facturation</label>
    <nameField>
        <label>Ligne Facturation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneFacturation__c/fields/Finance__c.field-meta.xml
<CustomField>
    <fullName>Finance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance</label>
    <referenceTo>facture_devis__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP02CloneLigneFacturationTEST.cls
@isTest
public with sharing class AP02CloneLigneFacturationTEST {
    static List<facture_devis__c> lstdevis ;
    static List<LigneFacturation__c> lstLigneFac ;

    static{
        lstdevis= new List<facture_devis__c>{
            new facture_devis__c(Name =  'TEST'),
            new facture_devis__c(Name =  'TEST2')
        };
        insert lstdevis;

        lstLigneFac = new List<LigneFacturation__c>{
            new LigneFacturation__c(Name =  'TEST',Finance__c=lstdevis[0].Id),
            new LigneFacturation__c(Name =  'TEST2',Finance__c=lstdevis[0].Id)
        };

        insert lstLigneFac;

    }

    @isTest
    public static void testCloneLigneFacturation(){
        Test.startTest();
        AP02CloneLigneFacturation.InputWrapper inp = new AP02CloneLigneFacturation.InputWrapper();
        inp.idDevisToClone = lstdevis[0].Id;
        inp.newDevis = lstdevis[1].Id;
        List<AP02CloneLigneFacturation.InputWrapper> lstInp = new List<AP02CloneLigneFacturation.InputWrapper>{inp};
        AP02CloneLigneFacturation.cloneLigneFacturation(lstInp);
        Test.stopTest();
    }
}