force-app/main/default/objects/facture_devis__c/facture_devis__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Numéro de devis / facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/facture_devis__c/fields/Contrevaleur_montant_total_PEC_c__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC_c__c</fullName>
    <label>Contrevaleur en euros estimée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/montant_total__c.field-meta.xml
<CustomField>
    <fullName>montant_total__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/recordTypes/Facture.recordType-meta.xml
<RecordType>
    <fullName>Facture</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/LigneFacturation__c/LigneFacturation__c.object-meta.xml
<CustomObject>
    <label>Ligne de facturation</label>
    <nameField>
        <label>Ligne Facturation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LigneFacturation__c/fields/Contrevaleur_montant_total_PEC__c.field-meta.xml
<CustomField>
    <fullName>Contrevaleur_montant_total_PEC__c</fullName>
    <formula>Montant_total_PEC_devises__c * Taux_change__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrevaleur du montant total PEC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Copaiement_devises__c.field-meta.xml
<CustomField>
    <fullName>Copaiement_devises__c</fullName>
    <formula>Montant_total_devises__c -  Montant_total_PEC_devises__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Copaiement en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Finance__c.field-meta.xml
<CustomField>
    <fullName>Finance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance</label>
    <referenceTo>facture_devis__c</referenceTo>
    <relationshipLabel>Lignes de facturation</relationshipLabel>
    <relationshipName>Lignes_facturation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Montant_total_devises__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_devises__c</fullName>
    <label>Montant total en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Montant_total_PEC_devises__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_PEC_devises__c</fullName>
    <formula>IF((ISNULL(Plafond_devises__c)|| (Plafond_devises__c==0)), Montant_total_devises__c  * Pourcentage_PEC__c,IF( Montant_total_devises__c&gt; Plafond_devises__c , Plafond_devises__c* Pourcentage_PEC__c, Montant_total_devises__c  * Pourcentage_PEC__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant total PEC en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Plafond_devises__c.field-meta.xml
<CustomField>
    <fullName>Plafond_devises__c</fullName>
    <label>Plafond en devises</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LigneFacturation__c/fields/Pourcentage_PEC__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_PEC__c</fullName>
    <label>Pourcentage de PEC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/AP03_LigneFacturation_TEST.cls
@isTest
public class AP03_LigneFacturation_TEST {
    static List<LigneFacturation__c> lstLigneFac = new List<LigneFacturation__c>();
    static List<facture_devis__c> lstFac = new List<facture_devis__c>();

    static{
        lstFac.add(new facture_devis__c (
            Name='test facture',
            montant_total__c=0,
            Montant_pris_en_charge__c=0,
            Montant_copay__c=0,
            Contrevaleur_montant_total_PEC_c__c=0
        ));
        insert lstFac;

        lstLigneFac.add(new LigneFacturation__c(
            Name='test ligne de facturation',
            Montant_total_devises__c=10,
            Pourcentage_PEC__c = 10,
            Plafond_devises__c=10,
            Finance__c = lstFac[0].Id
            // Montant_total_PEC_devises__c = 0, // formula field
            // Contrevaleur_montant_total_PEC__c=0 // formula field
        ));
        insert lstLigneFac;
    }

    // Test method for updateLigneDeFacture
    @isTest static void testUpdateLigneDeFacture() {
        // LigneFacturation__c testLine = lstLigneFac[0];
        LigneFacturation__c testLine = [SELECT Id,Finance__c, Plafond_devises__c, Name, Montant_total_devises__c,Pourcentage_PEC__c,Montant_total_PEC_devises__c,Copaiement_devises__c, Contrevaleur_montant_total_PEC__c FROM LigneFacturation__c][0];
        
        // Perform update operation
        testLine.Plafond_devises__c = 1234;
        String jsonString = JSON.serialize(new List<LigneFacturation__c>{testLine});
        Test.startTest();
        AP03_LigneFacturation.updateLigneDeFacture(jsonString);
        Test.stopTest();
        
        // Verify the update
        LigneFacturation__c updatedLine = [SELECT Plafond_devises__c FROM LigneFacturation__c WHERE Id = :testLine.Id];
        System.assertEquals(1234, updatedLine.Plafond_devises__c);
    }

    // Test method for deleteLigneDeFacture
    @isTest static void testDeleteLigneDeFacture() {
        // LigneFacturation__c testLine = lstLigneFac[0];
        LigneFacturation__c testLine = [SELECT Id,Finance__c, Plafond_devises__c, Name, Montant_total_devises__c,Pourcentage_PEC__c,Montant_total_PEC_devises__c,Copaiement_devises__c, Contrevaleur_montant_total_PEC__c FROM LigneFacturation__c][0];
        
        // Perform delete operation
        Test.startTest();
        AP03_LigneFacturation.deleteLigneDeFacture(JSON.serialize(testLine));
        Test.stopTest();
        
        // Verify the delete
        List<LigneFacturation__c> queryResults = [SELECT Id FROM LigneFacturation__c WHERE Id = :testLine.Id];
        System.assertEquals(0, queryResults.size());
    }
}