force-app/main/default/objects/facture_devis__c/facture_devis__c.object-meta.xml
<CustomObject>
    <label>Finance</label>
    <nameField>
        <label>Numéro de devis / facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/facture_devis__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analyse</fullName>
            </value>
            <value>
                <fullName>Prise en charge</fullName>
            </value>
            <value>
                <fullName>Consultation medicale</fullName>
                <label>Consultation médicale</label>
            </value>
            <value>
                <fullName>Conformite</fullName>
                <label>Conformité</label>
            </value>
            <value>
                <fullName>Traitement</fullName>
            </value>
            <value>
                <fullName>Controle</fullName>
                <label>Contrôle</label>
            </value>
            <value>
                <fullName>Paiement_Facturation</fullName>
                <label>Paiement / Facturation</label>
            </value>
            <value>
                <fullName>Bon a payer</fullName>
                <isActive>false</isActive>
                <label>Bon à payer</label>
            </value>
            <value>
                <fullName>Devis rejete</fullName>
                <isActive>false</isActive>
                <label>Devis rejeté</label>
            </value>
            <value>
                <fullName>Devis valide</fullName>
                <isActive>false</isActive>
                <label>Devis validé</label>
            </value>
            <value>
                <fullName>Echec Paiement</fullName>
                <isActive>false</isActive>
                <label>Echec Paiement</label>
            </value>
            <value>
                <fullName>En attente demande de pieces</fullName>
                <isActive>false</isActive>
                <label>En attente demande de pièces</label>
            </value>
            <value>
                <fullName>En attente validation medicale</fullName>
                <isActive>false</isActive>
                <label>En attente validation médicale</label>
            </value>
            <value>
                <fullName>Envoye Ebury</fullName>
                <isActive>false</isActive>
                <label>Envoyé Ebury</label>
            </value>
            <value>
                <fullName>Facture payee</fullName>
                <isActive>false</isActive>
                <label>Facture payée</label>
            </value>
            <value>
                <fullName>Facture refacturee</fullName>
                <isActive>false</isActive>
                <label>Facture refacturée</label>
            </value>
            <value>
                <fullName>Facture rejetee</fullName>
                <isActive>false</isActive>
                <label>Facture rejetée</label>
            </value>
            <value>
                <fullName>Mise en paiement</fullName>
                <isActive>false</isActive>
                <label>Mise en paiement</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
                <isActive>false</isActive>
                <label>Qualification</label>
            </value>
            <value>
                <fullName>Remboursement refacture</fullName>
                <isActive>false</isActive>
                <label>Remboursement refacturé</label>
            </value>
            <value>
                <fullName>Remboursement rejete</fullName>
                <isActive>false</isActive>
                <label>Remboursement rejeté</label>
            </value>
            <value>
                <fullName>Rembourse</fullName>
                <isActive>false</isActive>
                <label>Remboursé</label>
            </value>
            <value>
                <fullName>Validation DG</fullName>
                <isActive>false</isActive>
                <label>Validation DG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/facture_devis__c/fields/TECH_statusbar__c.field-meta.xml
<CustomField>
    <fullName>TECH_statusbar__c</fullName>
    <label>TECH_statusbar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/facture_devis__c/recordTypes/Facture.recordType-meta.xml
<RecordType>
    <fullName>Facture</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/facture_devis__c/recordTypes/Remboursement.recordType-meta.xml
<RecordType>
    <fullName>Remboursement</fullName>
    <active>true</active>
    <label>Remboursement</label>
</RecordType>

force-app/main/default/classes/AP01_FinanceUtils_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-07-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public with sharing class AP01_FinanceUtils_Test {
    @testSetup
    static void setupTestData() {
        Id factureRecordTypeId = Schema.SObjectType.facture_devis__c.getRecordTypeInfosByName().get('Facture').getRecordTypeId();
        Id otherRecordTypeId = Schema.SObjectType.facture_devis__c.getRecordTypeInfosByName().get('Remboursement').getRecordTypeId();
        List<facture_devis__c> testData = new List<facture_devis__c>();
        system.debug(factureRecordTypeId);
        // Create records for 'Facture' record type
        testData.add(new facture_devis__c(
            RecordTypeId = factureRecordTypeId,
            Statut__c = 'Envoye Ebury',
            TECH_statusbar__c = '["", "", "", "", "", "", "", "", ""]'
        ));
        testData.add(new facture_devis__c(
            RecordTypeId = factureRecordTypeId,
            Statut__c = 'Envoye Ebury',
            TECH_statusbar__c = '["", "", "", "", "", "", "", "", ""]'
        ));

        // Create records for other record type
        testData.add(new facture_devis__c(
            RecordTypeId = otherRecordTypeId,
            Statut__c = 'Envoye Ebury',
            TECH_statusbar__c = '["", "", "", "", "", "", "", "", ""]'
        ));
        testData.add(new facture_devis__c(
            RecordTypeId = otherRecordTypeId,
            Statut__c = 'Envoye Ebury',
            TECH_statusbar__c = '["", "", "", "", "", "", "", "", ""]'
        ));

        insert testData;
    }

    @isTest
    static void testSaveStatusBar() {
        List<facture_devis__c> lstFin = [SELECT Id, RecordTypeId, Statut__c, TECH_statusbar__c FROM facture_devis__c];
         // Update records to trigger the before update logic
         for(facture_devis__c fin : lstFin) {
            if(fin.RecordTypeId == Schema.SObjectType.facture_devis__c.getRecordTypeInfosByName().get('Facture').getRecordTypeId()) {
                fin.Statut__c = 'Facture payee';
            } else {
                fin.Statut__c = 'Rembourse';
            }
        }
        lstFin[0].Statut__c = 'Echec Paiement';
        lstFin[2].Statut__c = 'Echec Paiement';
        Test.startTest();
        update(lstFin);
        Test.stopTest();

        // Re-query the records to verify changes
        // lstFin = [SELECT Id, RecordTypeId, Statut__c, TECH_statusbar__c FROM facture_devis__c];

        // for(facture_devis__c fin : lstFin) {
        //     String recName = Schema.SObjectType.facture_devis__c.getRecordTypeInfosById().get(fin.RecordTypeId).getName();
        //     String[] outputArray = fin.TECH_statusbar__c.substring(1, fin.TECH_statusbar__c.length() - 1).split(',');
        //     system.debug('test tech');
        //     system.debug(fin);
        //     system.debug('test array');
        //     system.debug(outputArray);
        //     // if(recName == 'Facture') {
        //     //     if(fin.Statut__c == 'Echec Paiement') {
        //     //         System.assert(outputArray.size()>0, 'Expected more than 0 Ids.');
        //     //     }
        //     //     if(fin.Statut__c == 'Facture payee') {
        //     //         System.assert(outputArray.size()>0, 'Expected more than 0 Ids.');
        //     //     }
        //     // } else {
        //     //     if(fin.Statut__c == 'Rembourse') {
        //     //         System.assert(outputArray.size()>0, 'Expected more than 0 Ids.');
        //     //     }
        //     //     if(fin.Statut__c == 'Echec Paiement') {
        //     //         System.assert(outputArray.size()>0, 'Expected more than 0 Ids.');
        //     //     }
        //     // }
        // }
    }
}