force-app/main/default/objects/Lot_paiement__c/Lot_paiement__c.object-meta.xml
<CustomObject>
    <label>Lot de paiement</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot de paiements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot_paiement__c/fields/Error_message__c.field-meta.xml
<CustomField>
    <fullName>Error_message__c</fullName>
    <label>Error message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Montant_total__c.field-meta.xml
<CustomField>
    <fullName>Montant_total__c</fullName>
    <label>Montant total en euros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Montant_total_en_euros_valide__c.field-meta.xml
<CustomField>
    <fullName>Montant_total_en_euros_valide__c</fullName>
    <label>Montant total en euros validé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Nombre_elements__c.field-meta.xml
<CustomField>
    <fullName>Nombre_elements__c</fullName>
    <label>Nombre d’éléments dans lot de paiement</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Plafond_autorise__c.field-meta.xml
<CustomField>
    <fullName>Plafond_autorise__c</fullName>
    <defaultValue>550000</defaultValue>
    <label>Plafond autorisé</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Pret_Refacturation__c.field-meta.xml
<CustomField>
    <fullName>Pret_Refacturation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Prêt Refacturation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lot_paiement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
                <default>true</default>
                <label>Qualification</label>
            </value>
            <value>
                <fullName>Pret</fullName>
                <label>Prêt</label>
            </value>
            <value>
                <fullName>Envoye Ebury</fullName>
                <label>Envoyé Ebury</label>
            </value>
            <value>
                <fullName>Traitement</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Paiement</fullName>
            </value>
            <value>
                <fullName>Echec</fullName>
            </value>
            <value>
                <fullName>A payer</fullName>
                <isActive>false</isActive>
                <label>A payer</label>
            </value>
            <value>
                <fullName>A synchroniser</fullName>
                <isActive>false</isActive>
                <label>A synchroniser</label>
            </value>
            <value>
                <fullName>Echec paiement</fullName>
                <isActive>false</isActive>
                <label>Echec paiement</label>
            </value>
            <value>
                <fullName>En cours de synchronisation</fullName>
                <isActive>false</isActive>
                <label>En cours de synchronisation</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
            <value>
                <fullName>Traité</fullName>
                <isActive>false</isActive>
                <label>Traité</label>
            </value>
            <value>
                <fullName>Validé</fullName>
                <isActive>false</isActive>
                <label>Validé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP_LotDePaiementUtils.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-06-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class AP_LotDePaiementUtils {
   
    @AuraEnabled
    public static Lot_paiement__c getLDP(String recordId) {
            // Use bind variable to prevent SOQL injection
            String query = 'SELECT Id, Plafond_autorise__c, Montant_total__c, Montant_total_en_euros_valide__c, Nombre_elements__c, Pret_Refacturation__c, Error_message__c, Statut__c FROM Lot_paiement__c WHERE Id = :recordId LIMIT 1';
            Lot_paiement__c ldp = Database.query(query);
            System.debug(ldp);
            return ldp;
    }
    @AuraEnabled
    public static String savePlafond(String recordId, Double plafondValue) {
        // Your logic to save the plafond value
        Lot_paiement__c ldp = new Lot_paiement__c(
            Id=recordId,
            Plafond_autorise__c = plafondValue
        );
        update ldp;
        // Return a success message or result
        return 'Plafond saved successfully';
    }
    @AuraEnabled
    public static string savePretRefacturation(String recordId, Boolean value){
        // Your logic to save the plafond value
        Lot_paiement__c ldp = new Lot_paiement__c(
            Id=recordId,
            Pret_Refacturation__c = value
        );
        update ldp;
        // Return a success message or result
        return 'Prêt Pour Refacturation saved successfully';
    }
}