force-app/main/default/objects/Lot_paiement__c/Lot_paiement__c.object-meta.xml
<CustomObject>
    <label>Lot de paiement</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lot de paiements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lot_paiement__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
                <default>true</default>
                <label>Qualification</label>
            </value>
            <value>
                <fullName>Pret</fullName>
                <label>Prêt</label>
            </value>
            <value>
                <fullName>Envoye Ebury</fullName>
                <label>Envoyé Ebury</label>
            </value>
            <value>
                <fullName>Traitement</fullName>
            </value>
            <value>
                <fullName>Confirmation</fullName>
            </value>
            <value>
                <fullName>Paiement</fullName>
            </value>
            <value>
                <fullName>Echec</fullName>
            </value>
            <value>
                <fullName>A payer</fullName>
                <isActive>false</isActive>
                <label>A payer</label>
            </value>
            <value>
                <fullName>A synchroniser</fullName>
                <isActive>false</isActive>
                <label>A synchroniser</label>
            </value>
            <value>
                <fullName>Echec paiement</fullName>
                <isActive>false</isActive>
                <label>Echec paiement</label>
            </value>
            <value>
                <fullName>En cours de synchronisation</fullName>
                <isActive>false</isActive>
                <label>En cours de synchronisation</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
            <value>
                <fullName>Traité</fullName>
                <isActive>false</isActive>
                <label>Traité</label>
            </value>
            <value>
                <fullName>Validé</fullName>
                <isActive>false</isActive>
                <label>Validé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP01LotDePaiement.cls
public with sharing class AP01LotDePaiement {
   @AuraEnabled(Cacheable=true)
    public static List<PicklistWrapper> getPicklistValue(String objectName, String fieldName) {
        List<PicklistWrapper> lstPicklist = new List<PicklistWrapper>();
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(fieldName).getDescribe();
        for (Schema.PicklistEntry pickListVal : fieldResult.getPicklistValues()) {
            lstPicklist.add(new PicklistWrapper(pickListVal.getLabel(), pickListVal.getValue()));
        }
        return lstPicklist;
    }

    private class PicklistWrapper{
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
        public PicklistWrapper(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

    @AuraEnabled(Cacheable=false)
    public static void updateRecord(String rId, String stat){
        List<Lot_paiement__c> lstLotPaiement = new List<Lot_paiement__c>{
            new Lot_paiement__c(id = rId,Statut__c=stat)
        };
        if(!lstLotPaiement.isEmpty()) update lstLotPaiement;
    }


    @AuraEnabled
    public static string getReportUrl(){
        List<Report> lstReport = [SELECT id from Report WHERE DeveloperName= 'Rapport_re_facturation_GC'];
        if(lstReport.isEmpty()) return '';
        return lstReport[0]?.id;
        
    }
}